config/routes.rb
SuperHeroes::Application.routes.draw do

  get "/movies/search" => "movies#search"

  resources :movies do
    resources :reviews
  end

  namespace :admin do
    resources :users
  end

  resources :votes, only: [:update, :create]

  devise_for :users
  root to: "welcome#index"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, presence: true, uniqueness: {scope: :year}
  validates :superhero, presence: true
  validates :year, presence: true, length: {is: 4}
  validates :user, presence: true

  validates :mpaa_rating, inclusion: {in: ["G", "PG", "PG-13", "R", "NC-17", "", nil]}

  has_many :reviews, dependent: :destroy
  belongs_to :user

  paginates_per 10

  def average_rating
    if reviews.count > 0
      ratings = reviews.pluck(:rating)
      (ratings.reduce(:+)/1.0/ratings.length).round(2)
    else
      0
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating,
    presence: true,
    numericality: true,
    inclusion: { in: (0..5) }
  validates :movie, presence: true
  validates :user, presence: true

  belongs_to :movie
  belongs_to :user, foreign_key: "author_id"
  belongs_to :author, class_name: :User, foreign_key: "author_id"

  has_many :votes, dependent: :destroy

  validates :movie, presence: true

  # paginates_per 10

  def net_votes
    @net_votes ||= calculate_votes
  end

  def up_votes_count
    votes.where(value: "Up").count
  end

  def down_votes_count
    votes.where(value: "Down").count
  end

  def calculate_votes
    if self.votes.count == 0
      0
    else
      up_votes_count - down_votes_count
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes, dependent: :nullify
  validates :username, presence: true, uniqueness: true
  has_many :movies, dependent: :nullify
  has_many :reviews, foreign_key: :author_id, dependent: :nullify

  paginates_per 10
  mount_uploader :profile_photo, ProfilePhotoUploader
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :value, presence: true, inclusion: {in: ['Up', 'Down']}

  belongs_to :review
  belongs_to :user

  validates :user, presence: true
  validates :review, presence: true
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :validate_admin

    def index
      @users = User.all.page(params[:page])
    end

    def destroy
      @user = User.find(params[:id])

      if @user.destroy
        flash[:notice] = 'User successfully deleted.'
      else
        flash[:alert] = 'User was not deleted.'
      end

      redirect_to admin_users_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :profile_photo]

  end

  def admin?
    true if current_user.role == 'admin'
  end

  def validate_admin
    if !user_signed_in?
      redirect_to new_user_session_path, notice: 'Please sign in or sign up to continue.'
    elsif current_user.role != 'admin'
      redirect_to root_path, alert: 'Unauthorized access.'
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include RottenTomatoes

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @movies = Movie.all.page(params[:page])
  end

  def new
    @movie = Movie.new
  end


  def create
    if @movie.save
      flash[:notice] = 'Success! Your movie was saved.'
      redirect_to movie_path(@movie)
    else
      flash[:notice] = 'Movie could not be saved'
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = Kaminari.paginate_array(@movie.reviews.sort_by(&:net_votes).reverse!).page(params[:page]).per(10)
    # @reviews = Kaminari.paginate_array(@reviews).page(params[:page]).per(10)
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      flash[:notice] = "Movie successfully Deleted"
    else
      flash[:alert] = "Movie could not be Deleted"
    end

    redirect_to movies_path
  end


  def search
    Rotten.api_key = ENV['rotten_key']
    key_word = params[:q]
    @response = RottenMovie.find(title: key_word)

    if @response.blank?
      redirect_to new_movie_path, notice: "No movies found!"
    else
      movie = @response[0]
      new_movie = Movie.new(title: movie.title, year: movie.year.to_s, synopsis: movie.synopsis, mpaa_rating: movie.mpaa_rating, director: movie.director, superhero: key_word, user: current_user)

      if new_movie.save
        flash[:notice] = 'Success! Your movie was saved.'
        redirect_to movie_path(new_movie)
      else
        flash[:notice] = "Unable to save movie. Try again later!"
        render 'new'
      end
    end
  end


  private

  def movie_params
    params.require(:movie).permit(:title, :year, :superhero, :mpaa_rating, :synopsis, :director).merge(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @movie = Movie.find(params[:movie_id])
    redirect_to movie_path(@movie)
  end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.new(review_params)
    if @review.save
      flash[:notice] = 'Success! Your review was saved.'
      NewReviewAdded.receipt(@review).deliver
      redirect_to movie_path(@movie)
    else
      flash[:notice] = 'Review could not be saved.'
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    if @review.update(review_params) && current_user == @review.user
      flash[:notice] = 'Success! Your review was saved.'
      redirect_to movie_path(@movie)
    else
      flash[:notice] = 'Review could not be saved.'
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])

    if @review.destroy
      flash[:notice] = 'Review successfully deleted.'
    else
      flash[:notice] = 'Review could not be deleted.'
    end

    redirect_to movie_path(@movie)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body).merge(user: current_user)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!

  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      flash[:notice] = "Success! You voted."
    else
      flash[:notice] = "Your vote could not be saved."
    end
    redirect_to movie_path(@vote.review.movie)
  end

  def update
    @review = Review.find(params[:review_id])
    @vote = Vote.find_by(review: @review, user: current_user)
    if @vote.update(vote_params)
      flash[:notice] = "Success! You changed your vote."
    else
      flash[:notice] = "Your vote could not be saved."
    end
    redirect_to movie_path(@review.movie)
  end

  private

  def vote_params
    params.permit(:value).merge(user: current_user,
      review: Review.find(params[:review_id]))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @reviews = Review.order(created_at: :desc).limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    true if user_signed_in? && current_user.role == 'admin'
  end

  def user_vote_on(user, review)
    Vote.find_by(user: user, review: review)
  end

  def user_has_upvoted?(user, review)
    if user_vote_on(user, review).nil? || user_vote_on(user, review).value != "Up"
      false
    else
      true
    end
  end

end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/admin/users/index.html.erb
<h1>Welcome Admin!</h1>

<div class="users">
  <!-- Header rows -->
  <div class="row">
    <div class="small-2 columns">
      Username
    </div>
    <div class="small-3 columns">
      Email
    </div>
    <div class="small-1 columns">
      Review Count
    </div>
    <div class="small-3 columns">
      Last Sign In
    </div>
    <div class="small-1 columns">
      Sign In Count
    </div>
    <div class="small-2 columns">
      Delete?
    </div>
  </div>

  <!-- User information -->
  <% @users.each do |user| %>
    <div class="row" id=<%= "user_#{user.id}" %>>
      <div class="small-2 columns">
        <%= user.username %>
      </div>
      <div class="small-3 columns">
        <%= link_to user.email, "mailto:#{user.email}" %>
      </div>
      <div class="small-1 columns">
        <%= user.reviews.count %>
      </div>
      <div class="small-3 columns">
        <%= user.last_sign_in_at %>
      </div>
      <div class="small-1 columns">
        <%= user.sign_in_count %>
      </div>
      <div class="small-2 columns">
        <%= link_to 'Delete', admin_user_path(user), method: :delete %>
      </div>
    </div>
  <% end %>

  <%= paginate @users %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Super Superheroes" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Sniglet' rel='stylesheet' type='text/css'>
  </head>

  <body class="bg">

    <div class="row super-nav" data-equalizer>
      <div class="small-6 columns" data-equalizer-watch>
        <h1><%= link_to image_tag('logo.png'), root_path %></h1>
      </div>
      <div class="small-6 columns text-right super-nav-right" data-equalizer-watch>
        <% if user_signed_in? %>
          <%= link_to 'Add Movie', new_movie_path, class: "button alert tiny" %>
        <% end %>

        <%= link_to "Movies", movies_path, class: "button alert tiny" %>
        <% if user_signed_in? %>
          <%= link_to 'Edit Account', edit_user_registration_path, class: "button success tiny" %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "button success tiny" %>
        <% else %>
          <%=link_to 'Sign In', new_user_session_path, class: "button success" %>
          <%=link_to 'Sign Up', new_user_registration_path %>
        <% end %>
      </div>
    </div>

    <div class="row super">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :div, msg %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>

      <div class="small-10 columns small-centered">
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <%= f.input :title, required: true %>
  <%= f.input :year, required: true %>
  <%= f.input :superhero, required: true %>
  <%= f.input :mpaa_rating, label: 'MPAA rating' %>
  <%= f.input :director %>
  <%= f.input :synopsis %>
  <%= f.button :submit, 'Add Movie', class: "button" %>
<% end %>

<h1>OR</h1>
<h2>Find Movie From Rotten Tomatoes</h2>

<%= form_tag("/movies/search", method: 'get') do %>
  <%= label_tag(:q, "Find Movie") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>



<%# if !@titles.nil %>
<%#= f.select :title, @response.map { |movie| [movie.title, movie.id] }


<#%= f.select :role, Role.all.map { |r| [r.name, r.id, { class: r.company.id }] }, include_blank: true %>

<%#s= f.input :source_type, :label => "Lead or VTeam", :collection => ["lead","vteam"], :selected => "lead" %>

app/views/movies/index.html.erb
<h1 class="comic-title">Movies</h1>

<% if user_signed_in? %>
  <%= link_to "Add", new_movie_path, class: "button" %>
<% end %>

<table>
  <thead>
    <th>Title</th>
    <th>Year</th>
    <th>Superhero</th>
    <th>MPAA Rating</th>
    <th>Director</th>
    <th>Synopsis</th>
    <% if admin? %>
      <th>Delete</th>
    <% end %>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr id=<%= "movie_#{movie.id}" %>>
        <td>
          <%= link_to movie.title, movie_path(movie) %>
        </td>
        <td>
          <%= movie.year %>
        </td>
        <td>
          <%= movie.superhero %>
        </td>
        <td>
          <%= movie.mpaa_rating %>
        </td>
        <td>
          <%= movie.director %>
        </td>
        <td>
          <% if movie.synopsis != "" %>
            <%= truncate(movie.synopsis, length: 150) %>
            <%= link_to "read more", movie_path(movie) %>
          <% end %>
        </td>
        <% if admin? %>
          <td>
            <%= link_to 'Delete', movie_path(movie), method: :delete %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @movies %>

app/views/movies/new.html.erb
<h1 class="comic-title">Add a Movie</h1>
<%= render 'form' %>

app/views/movies/show.html.erb
<div class="movie">
  <h1 class="comic-title"><%= @movie.title %></h1>
  <p><%= link_to "Back to Movies", movies_path %></p>

  <table>
    <thead>
      <th>Year</th>
      <th>Hero</th>
      <th>MPAA</th>
      <th>Director</th>
      <th>Avg. Rating</th>
    </thead>

    <tbody>
      <tr>
        <td><%= @movie.year %></td>
        <td><%= @movie.superhero %></td>
        <td><%= @movie.mpaa_rating %></td>
        <td><%= @movie.director %></td>
        <td><%= @movie.average_rating %></td>
      </tr>
      <% if @movie.synopsis != "" %>
        <tr>
          <th colspan="5">Synopsis</th>
        </tr>
        <tr>
          <td colspan="5"><%= @movie.synopsis %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add Review', new_movie_review_path(@movie), class: "button" %>
  <% if admin? %>
    <%= link_to 'Delete Review', movie_path(@movie), method: :delete, class: "button alert" %>
  <% end %>
</div>

<% if !@movie.reviews.empty? %>
  <table class="reviews">
    <tbody>
      <% @reviews.each do |r| %>
        <tr id=<%= "review_#{r.id}" %>>
          <td>
            <% if user_signed_in? %>
              <% if user_vote_on(current_user, r) %>
                <% if user_has_upvoted?(current_user, r) %>
                  <div class="button tiny">Up (<%= r.up_votes_count %>)</div>
                  <%= link_to "Down (#{r.down_votes_count})", {action: "update",
                    controller: "votes", review_id: r.id, user_id: current_user.id, value: "Down"}, method: :put, class: "button tiny alert" %>
                <% else %>
                  <%= link_to "Up (#{r.up_votes_count})", {action: "update",
                    controller: "votes", review_id: r.id, user_id: current_user.id, value: "Up"}, method: :put, class: "button tiny success" %>
                    <div class="button tiny">Down (<%= r.down_votes_count %>)</div>
                <% end %>
              <% elsif current_user %>
                <%= link_to "Up (#{r.up_votes_count})", {action: "create",
                    controller: "votes", review_id: r.id, user_id: current_user.id, value: "Up"}, method: :post, class: "button tiny success" %>
                <%= link_to "Down (#{r.down_votes_count})", {action: "create",
                    controller: "votes", review_id: r.id, user_id: current_user.id, value: "Down"}, method: :post, class: "button tiny alert" %>
              <% end %>
            <% else %>
              <div class="button tiny">Up (<%= r.up_votes_count %>)</div>
              <div class="button tiny">Down (<%= r.down_votes_count %>)</div>
            <% end %>
          </td>
          <td>
            <%= r.rating %>/5
          </td>
          <td>
            <p><%= r.body %></p>
            <% if r.user == current_user || admin? %>
              <%= link_to 'Edit', edit_movie_review_path(id: r.id, movie_id: @movie.id) %>
              <%= link_to "Delete", { action: "destroy", controller: "reviews", id: r.id, movie_id: @movie.id }, method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tobdy>
  </table>

  <%= paginate @reviews %>
<% end %>

app/views/new_review_added/receipt.text.erb
Hello from your friends at Super Superheroes! Someone posted a review of <%= @review.movie.title %>. Why don't you go check it out?

app/views/reviews/_form.html.erb
<%= simple_form_for [@movie, @review] do |f| %>
  <%= f.input :rating, collection: 0..5, required: true %>
  <%= f.input :body, label: 'Review' %>
  <%= f.button :submit, 'Finish Review', class: "button" %>
<% end %>

app/views/reviews/_index.html.erb
<% @movie.reviews.each do |r| %>
  <p>Rating: <%= r.rating %></p>
  <p><%= r.body %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit This Review</h1>
<%= render 'form' %>

app/views/reviews/new.html.erb
<h1>Write a Review</h1>
<%= render 'form' %>

app/views/welcome/index.html.erb
<div class="row">
  <h1 class="comic-title">Welcome!</h1>
</div>

<div class="row">
  <div class="small-6 columns">
  <%= image_tag('green_lantern.png') %>
  </div>

  <div class="small-6 columns">
    <p>Have you ever wanted to review a movie? But not just any movie! A superhero movie!! But didn't want to share your valuable insights on lowly review websites like IMDB? Well rest assured, you don't have to!</p>
    <p>Leggings Tonx hella readymade disrupt. Post-ironic Helvetica sartorial organic selvage, selfies brunch dreamcatcher. Fanny pack Williamsburg polaroid fashion axe chambray, seitan gluten-free kitsch +1 salvia YOLO. Etsy shabby chic retro fanny pack, Truffaut Cosby sweater slow-carb typewriter twee bicycle rights Brooklyn hashtag Vice flannel. Flexitarian Pinterest master cleanse Bushwick fashion axe, sartorial four loko. Gentrify banh mi umami brunch, Carles butcher ethnic Banksy fap Vice cliche forage Pinterest. +1 McSweeney's ugh, chillwave sustainable asymmetrical Pitchfork banjo Williamsburg.</p>
  </div>
</div>

<div class="row">
  <h1 class="comic-title">Recent Reviews</h1>

  <table class="reviews">
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= link_to review.movie.title, movie_path(review.movie) %></td>
          <td><%= truncate(review.body, length: 250) %></td>
        </tr>
      <% end %>
    </tobdy>
  </table>
</div>